Controllers/CakeDetailController.cs
using Cake_Shope.Models;
using Microsoft.AspNetCore.Mvc;

namespace Cake_Shope.Controllers
{
    public class CakeDetailController : Controller
    {
        Products objmodel = new Products();
        public IActionResult Index()
        {
            objmodel = new Products();
            List<Products> lst = objmodel.getData();
            return View(lst);
        }
    }




}

Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Cake_Shope.Controllers
{
    public class ContactUsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ViewCartController.cs
using Microsoft.AspNetCore.Mvc;

namespace Cake_Shope.Controllers
{
    public class ViewCartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cake_Shope</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cake_Shope.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="./css/desktop-1.css" />
</head>
<body>
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cake_Shope</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AboutController1" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ContactUs" asp-action="Index">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product1" asp-action="Index">Our Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CakeDetail" asp-action="Index">Cake Detail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewCart" asp-action="Index">View Cart</a>
                        </li> 
                        <li class="nav-item">
                            <div class="order-cart-G3X"><a href="/Login" style="text-decoration:none ; color:black">Log in</a></div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  @*   <footer class="border-top footer text-muted">
        <div class="container">&copy; 2024 - cake_shope - <a asp-area="" asp-controller="home" asp-action="privacy">privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>